### ISSUE TITLE
[BUG]: directory structure of results becomes double nested

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/indexwc#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Thanks to @chantelwetzel-noaa for reporting that the directory structure of the results becomes double nested when the saved directory is not your current working directory.

### Expected Behavior

results should be saved in species_name/survey_name/index

### Environment

```markdown
- OS: any
- Node:
- npm:
```

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa I am not having this problem on my machine. Can you please provide a reproducible example? I am wondering if it is happening because of the use of here::* in some way? That is the only thing that I can think of but there could be plenty else that is going wrong. I passed a direct path and a relative path and neither led to the nested structure.

**Comment by chantelwetzel-noaa** [comment]
Thanks for following up on this. We sorted it out a while ago, but I forgot to close the issue.
