### ISSUE TITLE
[Feature]: save information from sanity() to a file

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/indexwc#31]
### Describe the problem your feature request is related to.

Often, when running multiple models or sending a finished model to someone else it would be good to have the output from `sanity()` saved to a text file that can easily be read back in.

### Describe the solution you'd like

Information saved in a file that can be batch read back in for multiple models.

### Describe alternatives you have considered

Require users to run the code on the saved model.

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa I am curious if we should save the information returned from `sanity()` which is just a list of logicals or if we should save the cli output that is printed to the screen to a file? Either is possible.

**Comment by chantelwetzel-noaa** [comment]
I am leaning towards saving the cli output as it is printed to the screen
